import crypto from "node:crypto";

// AES-256-GCM secret encryption for values this app stores at rest.
//
// ── WHY THIS IS A COPY, NOT AN IMPORT ────────────────────────────────────────
// The algorithm and the `iv:ciphertext:tag` hex wire format are deliberately
// byte-identical to the main SourceTrack API's encryptSecret/decryptSecret
// (api/lib/utils.js), which is what protects CAPI tokens, GSC and Stripe
// secrets there. Same class of protection, same well-reviewed construction.
//
// The KEY is deliberately NOT shared. This is a separate deployable with its
// own host and its own env, so it gets its own secret:
// SOURCETRACK_CONFIG_ENCRYPTION_KEY, never the API's ENCRYPTION_KEY. If this
// app's env ever leaks, the blast radius stops at the site keys stored here —
// it does not extend to every CAPI token and OAuth secret in the main
// platform. Two deployables, two keys.
//
// GCM (not CBC) so a tampered ciphertext fails the auth tag instead of
// decrypting to garbage that then gets POSTed somewhere as a "site key".
// ─────────────────────────────────────────────────────────────────────────────

const KEY_ENV_VAR = "SOURCETRACK_CONFIG_ENCRYPTION_KEY";

/**
 * Resolve the 32-byte key from the environment.
 *
 * Accepts 64 hex chars (`openssl rand -hex 32`) or 32 bytes base64
 * (`openssl rand -base64 32`) — the same two forms the main API accepts, so a
 * key generated by either documented command works.
 *
 * Not cached: this runs once per settings save and once per paid order, not on
 * a hot path, and keeping the key out of module state means it is never held
 * longer than the call that needs it. Error messages name the variable, never
 * its value.
 */
function keyBuffer() {
  const raw = process.env[KEY_ENV_VAR];
  if (!raw) {
    throw new Error(`${KEY_ENV_VAR} is not set — cannot encrypt or decrypt stored secrets.`);
  }

  if (/^[0-9a-fA-F]{64}$/.test(raw)) {
    return Buffer.from(raw, "hex");
  }

  const decoded = Buffer.from(raw, "base64");
  if (decoded.length === 32) {
    return decoded;
  }

  throw new Error(
    `${KEY_ENV_VAR} must be a 64-character hex string or a 32-byte base64 string.`,
  );
}

/**
 * Encrypt a secret for storage. Returns `iv:ciphertext:tag`, all hex.
 *
 * Throws if the key is missing or malformed. That is intentional: a caller that
 * cannot encrypt must fail the write, never fall back to storing plaintext.
 *
 * @param {string} plaintext
 * @returns {string}
 */
export function encryptSecret(plaintext) {
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv("aes-256-gcm", keyBuffer(), iv);
  let encrypted = cipher.update(String(plaintext), "utf8", "hex");
  encrypted += cipher.final("hex");
  const tag = cipher.getAuthTag().toString("hex");
  return `${iv.toString("hex")}:${encrypted}:${tag}`;
}

/**
 * Decrypt a value produced by encryptSecret.
 *
 * Throws on a bad format, a wrong key, or a tampered ciphertext — callers
 * decide what a failure means for their path rather than getting a plausible
 * looking wrong answer.
 *
 * @param {string} encrypted  `iv:ciphertext:tag`
 * @returns {string}
 */
export function decryptSecret(encrypted) {
  const parts = String(encrypted ?? "").split(":");
  if (parts.length !== 3) {
    throw new Error("Invalid encrypted value format — expected iv:ciphertext:tag.");
  }

  const decipher = crypto.createDecipheriv(
    "aes-256-gcm",
    keyBuffer(),
    Buffer.from(parts[0], "hex"),
  );
  decipher.setAuthTag(Buffer.from(parts[2], "hex"));
  let decrypted = decipher.update(parts[1], "hex", "utf8");
  decrypted += decipher.final("utf8");
  return decrypted;
}
